
name: Build and Deploy

on:
  push:
    branches:
      - main
      - build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: SCP files via ssh key
        uses: appleboy/scp-action@master
        env:
          USERNAME: ${{ secrets.SERVER_USER }}
          HOST: ${{ secrets.SERVER_HOST }}
          KEY: ${{ secrets.SERVER_KEY }}
        with:
          source: './dist'
          target: '/home/web/site232433/html/'