name: Build and Deploy

on:
  push:
    branches:
      - main
      - build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_KEY: ${{ secrets.SERVER_KEY }}
        run: |
          scp -i "$SERVER_KEY" -r dist/* $SERVER_USER@$SERVER_HOST:/home/web/site232433/html